Feat/signup
limdumb/HighEndy pull request #34
Opened 2023-04-15 08:57 UTC by limdumb

# 제목

* 회원가입 로직 구현

## 변경 내용

* 회원가입 함수 생성
* validate 함수 생성
* 에러코드 및 성공 메세지에 따른 핸들링
## 참고사항
* db도 Post요청이 가게되면 추가되는 상황이기 때문에 PR에 지속적으로 들어올수있음
* db는 추후 PR에서는 추가코드에 들어가지않게 처리할예정

2023-04-16 11:54 UTC, OrangeNebula requested changes

2023-04-16 11:54 UTC, OrangeNebula commented on src/API/auth/signup.ts
> +    console.error(error);
P5: 에러를 어떻게 처리 할 지에 대해 고민해보면 좋을 듯. 개발을 지속하면서 에러 처리에 대한 부분은 계속 챙겨나가야 하는 부분이라서! (단순히 console 로 에러를 찍는것히 회원가입 실패 에러 처리에 대한 최선일지?)

2023-04-16 11:54 UTC, OrangeNebula commented on src/API/instance.ts
>  export const baseInstance = axios.create({
P5: 에러 처리와 연결되는 부분인데, API 연동시 초반에 고려해두면 좋은게 공통에러 처리임 (e.g. 401, 500 에러에 대한 부분) 이런 에러 처리가 API 호출마다 추가되면 나중에 공통 로직이 변경되었을 때 수정해야 할 부분이 많아지게 됨. 공통에러 처리에 대한 부분을 어떻게 하면 좋을지 고민해보면 좋을 것

2023-04-16 11:54 UTC, OrangeNebula commented on src/components/common/AsideTab.tsx
> +  const memberId = localStorage.getItem("memberId"); // 추후 로그인 정보가 들어올 예정
P4: 지금은 localStorage 에서 값을 가져오지만 나중에는 어떻게 될 지 모를 수 있음. AsideTab 은 UI 를 관리하는 컴포넌트이므로, 데이터가 어디서 오는지까지 알게되는게 부적절할 수 있음. (SRP 위반), props 로 받거나, 혹은 유틸 함수, 혹은 상태관리 저장소, 혹은 repository 패턴을 도입해봄직할 듯.

2023-04-16 11:54 UTC, OrangeNebula commented on src/pages/SignUp.tsx
> +      case "nickName False":
P1: 유효성 검사 결과를 나타내는 별도의 객체를 생각해보는것이 좋을 것 같음. (e.g. 에러 객체, 가입 유효성 결과 객체). 단순 string 으로 핸들링하는 것은 깨지기 매우 쉬운 코드이기 때문. (e.g. 결과 string 이 달라졌다거나, 오타가 발생하거나, 텍스트 이외에 다른 결과가 필요하다거나)

2023-04-17 05:01 UTC, limdumb commented on src/API/auth/signup.ts
> +    console.error(error);
확인했습니다. 내용대로 공통에러처리를 생각하면서 코딩해야할것 같습니다. 그리고 console만으로는 회원가입 실패에대한 최선은 아닌듯싶고 조금더 고민해서 코드수정해보겠습니다

2023-04-17 05:36 UTC, limdumb commented on src/components/common/AsideTab.tsx
> +  const memberId = localStorage.getItem("memberId"); // 추후 로그인 정보가 들어올 예정
Props로 받는 부분으로 추후 리팩토링 진행하려고 했던 부분인데 뒤에 유틸함수,상태관리 저장소나 레파지토리 패턴도입도 한번 확인하면서 리팩토링 해봐야겠습니다! 확인했습니다!

2023-04-18 02:05 UTC, limdumb commented on src/pages/SignUp.tsx
> +      case "nickName False":
말씀하신대로 수정해봤습니다!

2023-04-19 01:54 UTC, merged