[Feat] useFetch함수 생성
limdumb/HighEndy pull request #47
Opened 2023-04-20 05:55 UTC by limdumb

# 제목

* useFetch 함수 생성

## 변경 내용

* Fetch Data를 받는 Custom Hook 생성

## 변경 이유

* 공용적으로 사용할수있는 데이터 Custom Hook을 사용하면 불필요한 작업을 줄있수있다고 생각하여 생성

2023-04-22 08:22 UTC, OrangeNebula requested changes

2023-04-22 08:22 UTC, OrangeNebula commented on src/components/customHook/useFetch.ts
> +  }, [endPoint, initialValue]);
P4: baseInstance 를 여기서 바로 import 해서 사용하는 방법도 있지만, 여기에 의존성을 추가하는 것도 방법이 될 듯

2023-04-22 08:22 UTC, OrangeNebula commented on src/components/customHook/useFetch.ts
> +  const [fetchData, setFetchData] = useState<State<T>>({
P2: 여기에 fetchData 가 상태값에 대한 이름으로 정의된 반면, 22번 라인에는 함수로도 사용중인 이름이므로, 다른 이름을 사용해보는걸로. (함수명을 바꾸거나, 상태값 명을 바꾸거나)

2023-04-23 00:11 UTC, limdumb commented on src/components/customHook/useFetch.ts
> +  }, [endPoint, initialValue]);
* 단순질문
* Params로 Base Instance를 받는게 아니고 Instance는 만들어 놓은 import 해서 사용해야 하는데 의존성 배열로 추적하는 이유가 어떻게 될까요?
@OrangeNebula

2023-04-23 00:12 UTC, limdumb commented on src/components/customHook/useFetch.ts
> +  const [fetchData, setFetchData] = useState<State<T>>({
수정 반영했습니다 :)

2023-04-23 01:38 UTC, merged